<!DOCTYPE html>
<html>
<head>
<title>MVC Perso</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Bootstrap -->
<link href="<?php echo Apps_Style; ?>bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
<link rel="stylesheet" type="text/css" href="<?php echo Apps_Style; ?>css/bootstrap.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Apps_Style; ?>bootstrap/css/bootstrap-responsive.css" />
<script type="text/javascript" src="<?php echo Apps_Style; ?>bootstrap/js/bootstrap.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo Apps_Style; ?>bootstrap/theme/css/general.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Apps_Style; ?>bootstrap/theme/css/footerSticky.css" />

</head>
<body>
<div class="container-fluid">
  <div class="row-fluid">
<div class="hero-unit span9">
  <h1 class="Gold">Acceuil du MVC . <small>Prototype V_RC_1.26.a</small></h1>
  <p></p>
  <div class="container">
        <p class="lead">MVC réalisé et adapté au besoin de la plateform RecruteAnim.</p>
        <p>Dépos : <a href="https://github.com/aangelus76/MVC_BASE">GitHub</a> sans support d'aide de réutilisation en dehors du projet.</p>
        <button type="button" data-toggle="modal" data-target="#myModal" class="btn-danger btn-large">Fenetre de Débug.</button>
     <?= $this->MsgError; ?>
  </div>
</div> 
<div class="well sidebar-nav offset1 span2">
        <ul class="nav nav-list text-left">
          <li class="nav-header"><i class="icon-align-justify icon-black"></i> Menu de BASE</li>
          <li><a href="<?= WEB_ROOT; ?>"><i class="icon-home icon-black"></i>Affiche Index.</a></li>
          <li><a href="<?= WEB_ROOT; ?>/rechercher"><i class="icon-search icon-black"></i>rechercher.</a></li>
          <li><a href="<?= WEB_ROOT; ?>/consulter"><i class="icon-eye-open icon-black"></i>consultation.</a></li>
          <li><a href="<?= WEB_ROOT; ?>/poster"><i class="icon-pencil icon-black"></i>Poster.</a></li>
          <li><a href="<?= WEB_ROOT; ?>/parametrer"><i class="icon-cog icon-black"></i>Configuration.</a></li>
          <li><a href="<?= WEB_ROOT; ?>/contacter"><i class="icon-envelope icon-black"></i>Contacter.</a></li>
          <li><a href="<?= WEB_ROOT; ?>/repertoire"><i class=" icon-user icon-black"></i>Voire mon répertoire.</a></li>
        </ul>
      </div>
</div></div>  
      
<?php echo $this->content(); ?> 
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> 
<!-- Include all compiled plugins (below), or include individual files as needed --> 
<div id="footer">
      <div class="container">
        <p class="text-muted credit">Copyright Angelus76 - <a href="http://www.recruteanim.fr">RecruteAnim</a>.</p>
      </div>
</div>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="<?php echo Apps_Style; ?>bootstrap/js/bootstrap.min.js"></script>
</body>
</html>