<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <div class="well sidebar-nav">
        <ul class="nav nav-list">
          <li class="nav-header">Menu de test</li>
          <li><a href="<?= WEB_ROOT; ?>">Affiche Index</a></li>
          <li><a href="<?= WEB_ROOT; ?>/poster">consultation</a></li>
          <li><a href="<?= WEB_ROOT; ?>/poster/offre/">Poster une offre</a></li>
          <li><a href="<?= WEB_ROOT; ?>/poster/candidature/">Poster une candidature</a></li>
          <li class="nav-header">Autres :</li>
          <li><a href="<?= WEB_ROOT; ?>/consulter/toto/">voire toto</a></li>
          <li><a href="<?= WEB_ROOT; ?>/consulterd">Erreur</a></li>
        </ul>
      </div>
    </div>
    <div class="span10">
      <div class="well text-success"> 
<?php
  echo $this->Msg;
?>
Menu de postage possible
</div>
    </div>
  </div>
</div>